"""Blog posts for Jhapher Malabanan SEO content system.

Each post is a light, useful guide with real next steps.
Avoid fake prices, guarantees, licenses, or overclaims.
"""

BLOG_POSTS = [
    {
        "slug": "septic-tank-warning-signs",
        "title": "5 Septic Tank Warning Signs Filipino Property Owners Should Know",
        "description": "Learn five septic tank warning signs, how they differ from a local drain clog, and what details to prepare before requesting service.",
        "eyebrow": "Homeowner education",
        "h1": "Five warning signs your septic system may need attention.",
        "intro": "Slow drains and odors are easy to ignore until they become disruptive. Here is how to read the pattern and know what information to prepare.",
        "category": "Warning signs",
        "summary": "A plain-language guide to slow drains, odors, gurgling, wet ground, overflow, and when a local clog may be the real issue.",
        "image": "assets/images/septic-system.webp",
        "lead": "A septic system usually gives clues before a serious backup. The challenge is that some signs can also come from a local drain blockage. Looking at the pattern across the property helps you describe the problem more accurately.",
        "sections": [
            ("1. More than one drain is moving slowly", "One slow sink can be a local obstruction. When toilets, floor drains, and sinks begin slowing at the same time, the issue may involve a larger wastewater line or reduced septic capacity."),
            ("2. Toilets gurgle or water returns elsewhere", "Gurgling can happen when air is displaced inside a restricted line. Water that rises in a floor drain while another fixture is used is an important detail to report during assessment."),
            ("3. Persistent wastewater odor develops", "A recurring smell near drains, the yard, or an access point deserves attention. It can be connected to drainage traps, venting, waste buildup, or a septic concern. Location and timing help narrow the possibilities."),
            ("4. Wet ground appears near the system", "Unexpected wet or unusually green areas can indicate excess moisture. Avoid opening or entering any tank. Keep people away from unsafe areas and request professional assessment."),
            ("5. Wastewater begins to back up", "Backup is the clearest reason to stop using affected fixtures where practical and call. Tell the team which fixtures are involved and whether the return is clear water or wastewater."),
        ],
        "callout_title": "Siphoning or declogging?",
        "callout_text": "If only one fixture is blocked, declogging may be the likely starting point. If several fixtures are affected, the tank is overdue for maintenance, or there are odor and overflow signs, septic assessment may also be needed.",
        "callout_href": "services.html",
        "callout_label": "Compare the services",
        "checklist": [
            "Exact city, barangay, and property type",
            "Which fixtures are affected",
            "When symptoms began and whether they are getting worse",
            "Safe photos of the access point or affected drain",
            "Any known maintenance history",
        ],
        "checklist_title": "What to send when requesting help",
        "related": [
            ("siphoning-vs-declogging.html", "Siphoning vs declogging"),
            ("septic-overflow-emergency-steps.html", "Overflow emergency steps"),
            ("prepare-for-septic-siphoning.html", "Prepare for siphoning"),
        ],
    },
    {
        "slug": "siphoning-vs-declogging",
        "title": "Siphoning vs Declogging: Which Service Do You Need?",
        "description": "Learn the difference between septic tank siphoning and drain declogging so you can describe your problem clearly and request the right help.",
        "eyebrow": "Service explainer",
        "h1": "Siphoning and declogging solve different problems.",
        "intro": "A blocked toilet is not always a full septic tank. Several slow fixtures are not always just one clog. Use this guide to choose a clearer starting point.",
        "category": "Service guide",
        "summary": "Understand when a local clog is likely, when tank maintenance may be needed, and what details help the assessment.",
        "image": "assets/images/declogging-equipment.webp",
        "lead": "Customers often ask for siphoning when the real issue is a local blockage, or ask for declogging when the septic tank is already full. Matching the service to the symptom pattern saves time and reduces repeat disruption.",
        "sections": [
            ("When declogging is often the starting point", "Declogging is usually the first discussion when one toilet, sink, or floor drain is blocked, water is standing in one area, or the rest of the property still drains normally."),
            ("When siphoning may be needed", "Siphoning becomes more likely when several fixtures slow down together, odor persists near the tank area, wastewater returns, the property has gone a long time without tank maintenance, or overflow signs appear."),
            ("Why the wrong first request happens", "The visible symptom can look the same. A toilet that will not flush can come from paper, wipes, or debris in the line, or from a system that no longer has enough capacity to accept more wastewater."),
            ("How to describe the issue clearly", "Tell the team whether one fixture or many are affected, whether odor is present, whether water returns through another drain, and when the problem started. That pattern is more useful than guessing the service name."),
            ("What happens after the first assessment", "The team reviews your details, discusses the likely service, and confirms access and schedule. If the on-site condition shows a different root cause, the scope can be clarified before extra work proceeds."),
        ],
        "callout_title": "Still unsure?",
        "callout_text": "Send your location, affected fixtures, and safe photos. A short symptom description is usually enough for a practical next-step recommendation.",
        "callout_href": "contact.html",
        "callout_label": "Request an assessment",
        "checklist": [
            "One fixture or several fixtures affected",
            "Odor, gurgling, overflow, or wastewater return",
            "Last known tank maintenance, if any",
            "City, barangay, and access-point photo",
        ],
        "checklist_title": "Details that help choose the right path",
        "related": [
            ("septic-tank-warning-signs.html", "Septic warning signs"),
            ("barado-ang-cr-ano-gagawin.html", "Barado ang CR guide"),
            ("septic-tank-siphoning.html", "Septic siphoning service"),
        ],
    },
    {
        "slug": "barado-ang-cr-ano-gagawin",
        "title": "Barado ang CR? Practical First Steps Before Calling for Help",
        "description": "Simple steps when your toilet is clogged: what to check, what to avoid, and when to request professional declogging or septic assessment.",
        "eyebrow": "Quick action guide",
        "h1": "Barado ang CR? Start with calm, useful checks.",
        "intro": "A clogged toilet is stressful, especially in a busy household. These first steps help you avoid making the backup worse while preparing useful details for service.",
        "category": "Declogging",
        "summary": "What to do first when the toilet will not flush, what not to pour, and when one blocked CR may signal a deeper drainage issue.",
        "image": "assets/images/declogging-equipment.webp",
        "lead": "Hindi lahat ng baradong CR ay kailangan agad ng septic siphoning. Minsan local clog lang. Minsan maraming fixtures ang apektado. Ang pattern ang mas importante kaysa panic.",
        "sections": [
            ("Stop adding more water when practical", "If the bowl is already high, avoid repeated flushing. Extra water can push the backup into the floor or another drain."),
            ("Check nearby fixtures", "Try a nearby sink or floor drain carefully. If several areas are slow or rising together, report that. It may not be a single toilet clog."),
            ("Avoid harsh chemical shortcuts", "Strong chemicals can damage pipes, create hazardous fumes, and still leave the obstruction in place. They also make later service harder if residue remains."),
            ("Gather clear details before you call", "Note when it started, whether anyone used wipes or thick paper, whether odor is present, and whether wastewater returns elsewhere."),
            ("Call sooner for overflow risk", "If water is returning, the floor is getting wet, or more than one bathroom is affected, request help promptly and reduce use of the affected fixtures."),
        ],
        "callout_title": "Need professional help?",
        "callout_text": "For a blocked toilet or drain, request declogging assessment. If several fixtures are affected, ask whether septic evaluation should be included.",
        "callout_href": "declogging-services.html",
        "callout_label": "View declogging service",
        "checklist": [
            "Which bathroom or fixture is blocked",
            "Whether other drains are also slow",
            "Any recent use of wipes, thick paper, or debris",
            "Safe photo of the affected area",
        ],
        "checklist_title": "Send these details on Viber or call",
        "related": [
            ("siphoning-vs-declogging.html", "Siphoning vs declogging"),
            ("blocked-sink-vs-septic-issue.html", "Blocked sink vs septic issue"),
            ("how-to-describe-clog-for-faster-help.html", "Describe a clog clearly"),
        ],
    },
    {
        "slug": "how-often-septic-tank-siphoning",
        "title": "How Often Should You Siphon a Septic Tank in the Philippines?",
        "description": "Learn what affects septic tank siphoning frequency for Filipino homes and businesses, including usage, tank size, warning signs, and maintenance history.",
        "eyebrow": "Maintenance guide",
        "h1": "Siphoning frequency depends on use, not a fixed calendar myth.",
        "intro": "There is no single schedule that fits every property. Household size, tank capacity, wastewater load, and warning signs all matter more than a copied rule.",
        "category": "Septic care",
        "summary": "A practical guide to septic maintenance timing for homes, rentals, and small commercial sites without fake one-size schedules.",
        "image": "assets/images/septic-system.webp",
        "lead": "Many property owners wait until backup happens. Others schedule too early without checking symptoms or history. A better approach is to combine known usage with visible warning signs and the last service date.",
        "sections": [
            ("What usually affects timing", "More people in the home, frequent guests, laundry load, food-business wastewater, and a smaller tank can all shorten the useful interval between services."),
            ("Why copied schedules can mislead", "A quiet two-person home and a busy boarding house do not age the same way. Using someone else's timeline without looking at your own symptoms can delay needed service or create unnecessary visits."),
            ("Better signals than the calendar alone", "Slow flushing across fixtures, recurring odor, gurgling, wet ground near the system, and a long gap since the last siphoning are stronger reasons to request assessment."),
            ("Rental and commercial properties", "Apartments, staff houses, and food sites often need closer attention because usage can spike without the owner noticing day to day."),
            ("How to plan without guessing", "Keep a simple record of the last service date, tank access location, and any recurring symptoms. Share that when requesting an estimate."),
        ],
        "callout_title": "Ready for an assessment?",
        "callout_text": "If you are unsure whether the tank is due, send your location, property type, last known service date, and current symptoms.",
        "callout_href": "septic-tank-siphoning.html",
        "callout_label": "Learn about siphoning",
        "checklist": [
            "Approximate household or occupant count",
            "Last known siphoning date, if available",
            "Current symptoms, if any",
            "Property type: home, rental, office, or business",
        ],
        "checklist_title": "Useful planning details",
        "related": [
            ("septic-tank-warning-signs.html", "Warning signs guide"),
            ("after-siphoning-what-to-expect.html", "After siphoning care"),
            ("landlord-septic-maintenance-checklist.html", "Landlord checklist"),
        ],
    },
    {
        "slug": "mabaho-ang-drain-sanhi-solusyon",
        "title": "Mabaho ang Drain? Common Causes and What To Do Next",
        "description": "Find practical next steps for foul drain odor in Filipino homes, including local trap issues, buildup, and when septic or pozo negro assessment may help.",
        "eyebrow": "Odor troubleshooting",
        "h1": "Mabaho ang drain? Trace the smell before guessing the fix.",
        "intro": "Drain odor can come from a dry trap, local buildup, venting issues, or a fuller wastewater system. Locating when and where the smell appears makes the next step clearer.",
        "category": "Warning signs",
        "summary": "A short guide to drain odor patterns, safer first checks, and when to request cleaning, declogging, or septic assessment.",
        "image": "assets/images/hero-service.webp",
        "lead": "Amoy wastewater does not always mean the septic tank is full. It also does not mean you should ignore it. The useful move is to note where the odor is strongest and whether drainage is also slowing.",
        "sections": [
            ("Note where the odor is strongest", "Is it only one sink, a floor drain, the CR, the yard, or near a manhole? Location helps separate a local issue from a broader system concern."),
            ("Check whether drainage is also slow", "Odor plus slow flow across several fixtures is different from odor in one rarely used drain. Report both symptoms together."),
            ("Common local contributors", "A dry floor-drain trap, food residue in kitchen lines, standing wastewater, or debris near a drain opening can create smell even when the tank is not the main issue."),
            ("When septic or pozo negro assessment matters", "Persistent odor near the tank area, wet ground, overflow history, or multiple affected fixtures should trigger a broader assessment conversation."),
            ("What not to do", "Do not open tanks, enter confined spaces, or pour unverified chemicals repeatedly. Keep the area ventilated and request help if the smell stays or worsens."),
        ],
        "callout_title": "Need a clearer next step?",
        "callout_text": "Send the odor location, affected fixtures, and any photos of the drain or access point. The team can help identify whether cleaning, declogging, or tank service is the practical path.",
        "callout_href": "contact.html",
        "callout_label": "Contact for assessment",
        "checklist": [
            "Where the smell is strongest",
            "Whether drains are also slow",
            "Indoor, outdoor, or both",
            "How long the odor has been present",
        ],
        "checklist_title": "Details worth sending",
        "related": [
            ("septic-tank-odor-outside-house.html", "Odor outside the house"),
            ("pozo-negro-vs-septic-tank.html", "Pozo negro vs septic"),
            ("pozo-negro-cleaning.html", "Pozo negro cleaning"),
        ],
    },
    {
        "slug": "prepare-for-septic-siphoning",
        "title": "How to Prepare for Septic Tank Siphoning: A Simple Checklist",
        "description": "Prepare for septic tank siphoning with a practical checklist covering location details, manhole access, parking, photos, and symptom notes.",
        "eyebrow": "Booking checklist",
        "h1": "A short preparation list makes siphoning smoother.",
        "intro": "Clear access and clear details help the team confirm scope before equipment arrives. Use this checklist before you request a schedule.",
        "category": "Booking guide",
        "summary": "What to prepare before septic siphoning so assessment, access, and scheduling are easier for homes and businesses.",
        "image": "assets/images/septic-system.webp",
        "lead": "Most delays happen before the work starts: unclear location, covered manholes, tight parking, or missing symptom details. A little preparation reduces back-and-forth.",
        "sections": [
            ("Confirm the exact property details", "Share city, barangay, subdivision or building name, gate instructions, and a useful landmark. For apartments or commercial sites, include the unit or wing if relevant."),
            ("Locate the manhole or access point", "If you know where the septic access is, take a safe photo. If it is covered by tiles, soil, or storage, mention that early so access can be discussed."),
            ("Check vehicle and hose approach", "Note narrow driveways, low clearance, parking limits, or long distance from the street to the tank access. Practical access affects planning."),
            ("Describe current symptoms", "Mention slow drains, odor, overflow history, or whether the visit is preventive maintenance. This helps confirm whether siphoning alone is the likely scope."),
            ("Decide who will be present", "Make sure someone can provide entry, point out the access, and confirm any on-site questions during the visit window."),
        ],
        "callout_title": "Ready to request service?",
        "callout_text": "Send the checklist details through call or Viber. For urgent overflow, call first.",
        "callout_href": "contact.html",
        "callout_label": "Prepare your request",
        "checklist": [
            "Exact address details and landmark",
            "Safe photo of the manhole or suspected access",
            "Parking or approach notes",
            "Symptoms or maintenance reason",
            "Preferred timing window",
        ],
        "checklist_title": "Pre-visit checklist",
        "related": [
            ("manhole-access-for-siphoning.html", "Manhole access tips"),
            ("after-siphoning-what-to-expect.html", "After siphoning"),
            ("septic-tank-siphoning.html", "Siphoning service page"),
        ],
    },
    {
        "slug": "septic-overflow-emergency-steps",
        "title": "Septic Overflow: What To Do First for Safety and Faster Help",
        "description": "Practical first steps during septic or wastewater overflow: reduce fixture use, keep people clear, gather details, and request urgent assessment.",
        "eyebrow": "Urgent guidance",
        "h1": "Overflow needs calm action, not risky DIY.",
        "intro": "Wastewater overflow is disruptive and potentially unsafe. Focus on reducing exposure, protecting the area, and sending clear details for faster coordination.",
        "category": "Urgent help",
        "summary": "Immediate actions for overflow or wastewater backup, plus the details that help a service team respond more usefully.",
        "image": "assets/images/hero-service.webp",
        "lead": "When wastewater returns through a drain, toilet, or outdoor area, the priority is safety and containment, not opening the tank yourself.",
        "sections": [
            ("Reduce use of affected fixtures", "Stop flushing and limit water use in the affected zone when practical. Extra flow can worsen the backup."),
            ("Keep people and pets away from unsafe areas", "Treat standing wastewater as a hazard. Do not let children play nearby. Avoid direct contact where possible."),
            ("Do not enter or open the tank", "Tank openings and confined spaces are dangerous. Leave inspection and handling to trained responders with the right setup."),
            ("Document what you can see safely", "Note which fixtures are overflowing, whether the return is wastewater, and whether outdoor wet areas appeared. Safe photos help."),
            ("Call with location and access details", "Share city, barangay, landmark, and whether equipment can approach. Urgent cases should start with a call rather than a long message thread."),
        ],
        "callout_title": "Need urgent assessment?",
        "callout_text": "Call first for overflow or active wastewater backup. Have your location and access notes ready.",
        "callout_href": "contact.html",
        "callout_label": "Contact now",
        "checklist": [
            "Which fixtures or areas are overflowing",
            "When it started",
            "Exact location and access notes",
            "Whether people are clear of the affected area",
        ],
        "checklist_title": "Have these ready when you call",
        "related": [
            ("septic-tank-warning-signs.html", "Earlier warning signs"),
            ("floor-drain-backup-causes.html", "Floor drain backup"),
            ("wet-ground-near-septic-tank.html", "Wet ground near tank"),
        ],
    },
    {
        "slug": "pozo-negro-vs-septic-tank",
        "title": "Pozo Negro vs Septic Tank: What Property Owners Should Know",
        "description": "Understand the practical difference between pozo negro and septic tank concerns, including odor, capacity, cleaning needs, and what details to share for assessment.",
        "eyebrow": "System basics",
        "h1": "Pozo negro and septic concerns can look similar from above ground.",
        "intro": "Property owners often use the terms interchangeably. What matters for service is access, symptoms, waste buildup, and whether cleaning or another response is needed.",
        "category": "Service guide",
        "summary": "A plain explanation of pozo negro and septic service concerns so you can describe your property more accurately.",
        "image": "assets/images/septic-system.webp",
        "lead": "You do not need perfect technical vocabulary to get help. You do need clear observations: odor, overflow, slow drainage, access point condition, and how the property is used.",
        "sections": [
            ("Why the labels get mixed", "In everyday conversation, people may say septic, pozo negro, or tank for the wastewater structure under the property. Service teams clarify based on site details, not labels alone."),
            ("Shared warning signs", "Odor, reduced capacity, overflow risk, and slow wastewater movement can appear in different system setups. The symptom pattern still guides the first assessment."),
            ("Why access matters so much", "Cleaning or siphoning depends on a usable access point and practical equipment approach. Covered, damaged, or hard-to-reach openings should be mentioned early."),
            ("Property use changes the load", "Homes, rentals, food businesses, and offices create different waste patterns. Higher load can mean faster buildup and earlier service needs."),
            ("What to say when requesting help", "Describe the structure as you know it, share photos of the access if safe, and explain the symptoms. The team can recommend cleaning, siphoning, or another next step."),
        ],
        "callout_title": "Need pozo negro cleaning assessment?",
        "callout_text": "Send your location, odor or overflow details, and a safe access photo so the likely scope can be discussed.",
        "callout_href": "pozo-negro-cleaning.html",
        "callout_label": "View pozo negro service",
        "checklist": [
            "Known system type, if any",
            "Odor, overflow, or slow-drainage symptoms",
            "Access-point photo",
            "Home, rental, or business use",
        ],
        "checklist_title": "Helpful assessment details",
        "related": [
            ("mabaho-ang-drain-sanhi-solusyon.html", "Drain odor guide"),
            ("septic-tank-siphoning.html", "Septic siphoning"),
            ("prepare-for-septic-siphoning.html", "Preparation checklist"),
        ],
    },
    {
        "slug": "slow-drains-multiple-fixtures",
        "title": "Slow Drains in Multiple Fixtures: What It Usually Means",
        "description": "Learn why several slow drains at once can signal a deeper wastewater issue, how it differs from one clogged sink, and what to report for assessment.",
        "eyebrow": "Diagnosis guide",
        "h1": "When several drains slow down together, pay attention.",
        "intro": "One slow sink is common. Multiple slow toilets, floor drains, and basins at the same time deserve a broader look.",
        "category": "Warning signs",
        "summary": "How to read multi-fixture drainage problems and decide whether declogging, septic assessment, or both may be needed.",
        "image": "assets/images/declogging-equipment.webp",
        "lead": "The number of affected fixtures is one of the most useful clues you can give a service team. It often separates a local clog from a shared line or tank-capacity concern.",
        "sections": [
            ("One fixture versus many", "A single kitchen sink may have food debris or a local trap issue. If the CR, bath, and floor drain also slow down, the shared path may be involved."),
            ("Watch for related symptoms", "Gurgling, odor, water rising in one drain when another is used, and recent overflow history make the case for faster assessment."),
            ("Why temporary plunging may not finish the job", "Clearing one fixture can help briefly if the deeper restriction remains. Track whether the improvement lasts across the property."),
            ("What to map before you call", "List every affected fixture, which floor or wing is involved, and whether outdoor wet areas appeared. A simple map in words is enough."),
            ("Possible service paths", "The next step may be declogging, septic siphoning, pozo negro cleaning, or a combination once the site condition is clearer."),
        ],
        "callout_title": "Share the pattern",
        "callout_text": "A short list of affected fixtures is often more useful than guessing the service name.",
        "callout_href": "services.html",
        "callout_label": "Compare services",
        "checklist": [
            "All affected fixtures",
            "Whether symptoms started together",
            "Odor or gurgling notes",
            "Property layout notes if multi-level",
        ],
        "checklist_title": "Report these observations",
        "related": [
            ("siphoning-vs-declogging.html", "Siphoning vs declogging"),
            ("gurgling-toilet-meaning.html", "Gurgling toilet meaning"),
            ("septic-tank-warning-signs.html", "Septic warning signs"),
        ],
    },
    {
        "slug": "what-not-to-flush-septic",
        "title": "What Not to Flush If You Have a Septic Tank",
        "description": "Practical flushing habits for septic systems: what to avoid, why wipes and grease cause trouble, and how better habits reduce repeat clogs.",
        "eyebrow": "Prevention guide",
        "h1": "Small flushing habits can prevent big drainage trouble.",
        "intro": "Septic and drainage systems handle wastewater, not trash. Knowing what to keep out of the toilet and sink reduces avoidable clogs and strain.",
        "category": "Prevention",
        "summary": "A clear list of items and habits that commonly contribute to clogs and septic stress in Filipino households.",
        "image": "assets/images/septic-system.webp",
        "lead": "Many backups start with everyday items that seem harmless. Wipes, thick paper, grease, and non-flushable products can accumulate and restrict flow.",
        "sections": [
            ("Keep non-flushables out of the toilet", "Wipes labeled flushable, sanitary products, cotton pads, dental floss, and paper towels do not break down like toilet paper and can create stubborn clogs."),
            ("Treat kitchen grease as a drain risk", "Cooking oil and grease can coat pipes and trap debris. Let grease cool and dispose of it with solid waste instead of washing it down."),
            ("Be careful with food scraps", "Rice, coffee grounds, and fibrous scraps can build up in kitchen lines. A strainer helps more than repeated hot-water shortcuts."),
            ("Watch household chemical overload", "Repeated harsh chemical dumping is not a maintenance plan. It can create hazards and still leave physical blockages in place."),
            ("Create a simple house rule", "Post a short note in rental units or staff restrooms: toilet paper only, no wipes, no grease. Prevention is cheaper than emergency disruption."),
        ],
        "callout_title": "Already dealing with a clog?",
        "callout_text": "If fixtures are already slow or blocked, request assessment rather than waiting for a full backup.",
        "callout_href": "declogging-services.html",
        "callout_label": "Request declogging help",
        "checklist": [
            "No wipes or sanitary products in the toilet",
            "No grease poured into sinks",
            "Use sink strainers where practical",
            "Remind household members or tenants",
        ],
        "checklist_title": "Prevention checklist",
        "related": [
            ("restaurant-kitchen-drain-care.html", "Kitchen drain care"),
            ("barado-ang-cr-ano-gagawin.html", "Barado ang CR guide"),
            ("landlord-septic-maintenance-checklist.html", "Landlord checklist"),
        ],
    },
    {
        "slug": "rainy-season-septic-problems",
        "title": "Rainy Season Septic and Drain Problems: What Homeowners Should Watch",
        "description": "Learn how heavy rain can worsen septic and drainage symptoms, what to monitor around your property, and when to request professional assessment.",
        "eyebrow": "Seasonal guide",
        "h1": "Heavy rain can reveal drainage weaknesses faster.",
        "intro": "During rainy months, some properties notice stronger odor, slower drains, or wetter ground near wastewater areas. Knowing what to watch helps you act earlier.",
        "category": "Seasonal care",
        "summary": "A rainy-season checklist for septic odor, wet ground, and drainage slowdowns without panic or unsafe DIY.",
        "image": "assets/images/hero-service.webp",
        "lead": "Rain does not create every septic problem, but it can make existing capacity or drainage issues more noticeable. Track changes instead of assuming it will pass on its own.",
        "sections": [
            ("Watch for new wet areas", "If ground near the tank or drainage path becomes unusually wet or soggy after rain, note it and keep people clear of unsafe spots."),
            ("Compare indoor drainage before and during storms", "If toilets and floor drains become slower only during heavy rain, include that timing when you request help."),
            ("Separate stormwater concerns from wastewater signs", "Flooding from poor surface drainage is different from wastewater backup. Describe color, odor, and which fixtures are involved."),
            ("Protect access points when possible", "Keep manholes identifiable and free from debris so service can proceed if assessment is needed. Do not open them casually."),
            ("Request help if odor or backup appears", "Persistent odor, indoor backup, or wastewater return should not wait for the weather to improve."),
        ],
        "callout_title": "Seeing rainy-season warning signs?",
        "callout_text": "Send photos of wet areas when safe, plus notes on indoor fixture behavior during rain.",
        "callout_href": "contact.html",
        "callout_label": "Request assessment",
        "checklist": [
            "Indoor drain behavior during rain",
            "Outdoor wet spots near the system",
            "Odor changes",
            "Safe photos and exact location",
        ],
        "checklist_title": "Seasonal observation list",
        "related": [
            ("wet-ground-near-septic-tank.html", "Wet ground near tank"),
            ("septic-overflow-emergency-steps.html", "Overflow steps"),
            ("septic-tank-warning-signs.html", "Warning signs"),
        ],
    },
    {
        "slug": "gurgling-toilet-meaning",
        "title": "Why Your Toilet Gurgles and When It Needs Attention",
        "description": "Understand common causes of a gurgling toilet, how it relates to drainage restriction, and what details to share before requesting declogging or septic help.",
        "eyebrow": "Symptom guide",
        "h1": "A gurgling toilet is a useful early warning.",
        "intro": "Gurgling often means air is moving through a restricted drainage path. It may start small, then appear with slow flushing or odor.",
        "category": "Warning signs",
        "summary": "What toilet gurgling can mean, which related symptoms matter, and when to request professional assessment.",
        "image": "assets/images/declogging-equipment.webp",
        "lead": "Do not ignore repeated gurgling, especially if nearby drains also complain. Early notes make later service faster and more accurate.",
        "sections": [
            ("What the sound often indicates", "Air displacement in a partially blocked or restricted line can create gurgles when water tries to pass."),
            ("Check neighboring fixtures", "If a sink or floor drain also gurgles or rises when the toilet is used, the issue may be shared rather than limited to one bowl."),
            ("Track timing and frequency", "Occasional sounds after heavy use are different from daily gurgling with slow recovery. Frequency helps the assessment."),
            ("Related red flags", "Combine gurgling with odor, multi-fixture slowdown, or wastewater return and you have a stronger reason to call sooner."),
            ("What to avoid", "Repeated forceful flushing and chemical dumping rarely solve a restriction and can worsen mess or hazard."),
        ],
        "callout_title": "Hearing repeated gurgling?",
        "callout_text": "Describe which fixtures gurgle, whether drainage is slow, and when it started. That is enough for a useful first conversation.",
        "callout_href": "declogging-services.html",
        "callout_label": "View declogging options",
        "checklist": [
            "Which fixtures gurgle",
            "Whether flushing is also slow",
            "Any water rising elsewhere",
            "When the sound became frequent",
        ],
        "checklist_title": "Notes worth saving",
        "related": [
            ("slow-drains-multiple-fixtures.html", "Multiple slow drains"),
            ("barado-ang-cr-ano-gagawin.html", "Barado ang CR"),
            ("siphoning-vs-declogging.html", "Siphoning vs declogging"),
        ],
    },
    {
        "slug": "wet-ground-near-septic-tank",
        "title": "Wet Ground Near a Septic Tank: What It Can Mean",
        "description": "Learn what unusually wet or soggy ground near a septic area may indicate, safety precautions to take, and when to request professional assessment.",
        "eyebrow": "Yard warning signs",
        "h1": "Unexpected wet ground near the tank deserves a closer look.",
        "intro": "A damp patch after rain can be normal surface water. Persistent soggy ground, odor, or lush wet spots near the system should not be ignored.",
        "category": "Warning signs",
        "summary": "How to observe wet ground near septic areas safely and what information to send when requesting help.",
        "image": "assets/images/septic-system.webp",
        "lead": "Do not dig toward the tank or open covers to investigate. Your job is safe observation and clear reporting.",
        "sections": [
            ("Compare with recent weather", "If the area stays wet long after surrounding ground dries, mention that timing. Persistent moisture is more useful than a one-day rain puddle."),
            ("Note odor and indoor symptoms", "Wet ground plus wastewater smell, slow indoor drains, or backup history strengthens the case for assessment."),
            ("Keep the area restricted", "Treat uncertain wet spots as off-limits for kids, pets, and foot traffic until the cause is clearer."),
            ("Do not excavate on your own", "Hidden lids, pipes, and unsafe openings are easy to disturb. Leave uncovering and inspection to professionals."),
            ("Send safe visual context", "A photo from a distance, landmark notes, and a description of size and smell help more than risky close contact."),
        ],
        "callout_title": "Need the area assessed?",
        "callout_text": "Share location, how long the ground has stayed wet, and any indoor drainage symptoms.",
        "callout_href": "contact.html",
        "callout_label": "Request help",
        "checklist": [
            "How long the wet area has been present",
            "Whether odor is noticeable",
            "Indoor fixture symptoms",
            "Safe distance photo if possible",
        ],
        "checklist_title": "Observation checklist",
        "related": [
            ("rainy-season-septic-problems.html", "Rainy season guide"),
            ("septic-overflow-emergency-steps.html", "Overflow steps"),
            ("septic-tank-warning-signs.html", "Five warning signs"),
        ],
    },
    {
        "slug": "apartment-building-drain-problems",
        "title": "Apartment and Building Drain Problems: A Practical Owner Guide",
        "description": "A practical guide for apartment owners and building managers facing shared drain slowdowns, toilet backups, and septic service coordination.",
        "eyebrow": "Property managers",
        "h1": "Shared buildings need clearer drainage coordination.",
        "intro": "In apartments and multi-unit sites, one clogged CR can affect neighbors quickly. Fast reporting and clear access details reduce downtime.",
        "category": "Property managers",
        "summary": "How building managers and landlords can gather unit reports, access notes, and symptom patterns before requesting service.",
        "image": "assets/images/declogging-equipment.webp",
        "lead": "Multi-unit problems are harder when each tenant describes a different piece of the puzzle. A simple building log helps the service team see the full pattern.",
        "sections": [
            ("Collect unit-level reports in one place", "Ask which units are affected, which fixtures, and when symptoms started. Shared timing often reveals a common line issue."),
            ("Identify access and entry constraints", "Note basement access, narrow alleys, parking limits, HOA rules, and who holds keys. Access delays are common in buildings."),
            ("Separate one-unit clogs from building-wide symptoms", "If only one toilet is blocked while others remain normal, local declogging may be the first step. If several units slow together, broader assessment is needed."),
            ("Communicate use restrictions quickly", "When backup risk is present, tell affected units to reduce flushing and water use until guidance is given."),
            ("Prepare one contact person", "A single coordinator who can approve entry and answer access questions speeds up the visit."),
        ],
        "callout_title": "Managing a multi-unit issue?",
        "callout_text": "Send a short summary of affected units, shared symptoms, and access constraints for a clearer assessment.",
        "callout_href": "contact.html",
        "callout_label": "Coordinate assessment",
        "checklist": [
            "List of affected units and fixtures",
            "Building entry and parking notes",
            "On-site contact person",
            "Safe photos of shared access if available",
        ],
        "checklist_title": "Building request checklist",
        "related": [
            ("landlord-septic-maintenance-checklist.html", "Landlord checklist"),
            ("commercial-property-declogging-guide.html", "Commercial declogging"),
            ("slow-drains-multiple-fixtures.html", "Multiple slow drains"),
        ],
    },
    {
        "slug": "restaurant-kitchen-drain-care",
        "title": "Restaurant and Kitchen Drain Care: Reduce Grease Clogs",
        "description": "Practical kitchen drain care for restaurants and food businesses, including grease habits, strainer use, warning signs, and when to request declogging.",
        "eyebrow": "Food business guide",
        "h1": "Busy kitchens need drain habits, not only emergency calls.",
        "intro": "Grease, food solids, and constant wash-down can strain kitchen lines. Simple daily habits reduce sudden closures caused by blocked drains.",
        "category": "Commercial care",
        "summary": "A light operations guide for food businesses dealing with slow floor drains, sink backups, and grease-related clog risk.",
        "image": "assets/images/declogging-equipment.webp",
        "lead": "When a kitchen floor drain backs up during service, the cost is more than cleanup. Prevention and early reporting keep disruption smaller.",
        "sections": [
            ("Stop grease at the source", "Wipe pans before washing and dispose of cooled grease with solid waste. Do not rely on hot water alone to carry fat through the line."),
            ("Use strainers consistently", "Sink and floor strainers only help if staff empty them. Make it part of closing checklist."),
            ("Watch for early service warnings", "Slow floor drains, recurring odor, or water pooling near prep areas should trigger a maintenance request before peak hours."),
            ("Schedule around operations when possible", "If drains are worsening, request assessment before a full backup hits lunch or dinner service."),
            ("Share business-use details when calling", "Mention kitchen line concerns, grease history, and access times. Food sites often need clearer timing coordination."),
        ],
        "callout_title": "Kitchen drain already slow?",
        "callout_text": "Request declogging assessment early and share your operating hours so scheduling can be discussed realistically.",
        "callout_href": "declogging-services.html",
        "callout_label": "Request kitchen drain help",
        "checklist": [
            "Which kitchen fixtures are slow",
            "Grease or food-solids history",
            "Best access window",
            "Photos of the affected drain when safe",
        ],
        "checklist_title": "Food-business details to send",
        "related": [
            ("what-not-to-flush-septic.html", "What not to put in drains"),
            ("commercial-property-declogging-guide.html", "Commercial declogging"),
            ("floor-drain-backup-causes.html", "Floor drain backup"),
        ],
    },
    {
        "slug": "landlord-septic-maintenance-checklist",
        "title": "Landlord Septic Maintenance Checklist for Rentals",
        "description": "A practical septic and drain checklist for landlords and property owners managing rentals, tenant communication, and service readiness.",
        "eyebrow": "Landlord guide",
        "h1": "Rental properties need a simple septic care system.",
        "intro": "Landlords often hear about drainage problems late. A short checklist for records, tenant rules, and service prep prevents avoidable emergencies.",
        "category": "Property managers",
        "summary": "Keep rental septic and drain issues manageable with maintenance notes, tenant guidance, and faster service coordination.",
        "image": "assets/images/septic-system.webp",
        "lead": "You do not need a complex facility system. You need dated service notes, clear tenant rules, and a fast way to gather symptoms when something goes wrong.",
        "sections": [
            ("Keep a one-page service record", "Store last siphoning date, access location notes, contractor contacts, and any recurring issues per unit or building."),
            ("Set clear flush and grease rules", "Tell tenants what not to flush and what not to pour. A simple move-in note prevents repeated avoidable clogs."),
            ("Ask for early symptom reports", "Encourage tenants to report slow drains and odor early, not only full backups. Early reports are cheaper than emergency mess."),
            ("Confirm access before scheduling", "Know who has keys, where the manhole is, and whether parking is restricted. This shortens confirmation time."),
            ("Decide urgency thresholds", "Overflow, wastewater return, or multi-unit slowdown should trigger immediate coordination rather than waiting for a routine slot."),
        ],
        "callout_title": "Need help for a rental property?",
        "callout_text": "Send the property location, tenant-reported symptoms, and any last service date you have on file.",
        "callout_href": "contact.html",
        "callout_label": "Request rental assessment",
        "checklist": [
            "Last known tank service date",
            "Tenant symptom summary",
            "Access and keyholder details",
            "Unit or building notes",
        ],
        "checklist_title": "Landlord quick checklist",
        "related": [
            ("how-often-septic-tank-siphoning.html", "Siphoning frequency"),
            ("apartment-building-drain-problems.html", "Apartment drain problems"),
            ("what-not-to-flush-septic.html", "What not to flush"),
        ],
    },
    {
        "slug": "manhole-access-for-siphoning",
        "title": "Manhole Access Tips Before Septic Siphoning",
        "description": "Practical manhole and septic access tips for homeowners before siphoning, including photos, covered lids, parking notes, and safety reminders.",
        "eyebrow": "Access guide",
        "h1": "Good access details make siphoning planning easier.",
        "intro": "If the team cannot confirm how to reach the tank opening, scheduling takes longer. These tips help you describe access clearly and safely.",
        "category": "Booking guide",
        "summary": "How to find, photograph, and describe septic access points without unsafe digging or confined-space risks.",
        "image": "assets/images/septic-system.webp",
        "lead": "Many homes have lids hidden by soil, planters, tiles, or storage. Mentioning that early is better than discovering it only when the truck is already expected.",
        "sections": [
            ("Look for known markers first", "Check old service notes, ask previous occupants, or look for circular covers in common yard or driveway locations. Do not force covers open."),
            ("Send a safe photo", "A clear photo from standing height helps more than a close shot taken while prying at a lid. Include nearby walls or gates for scale."),
            ("Describe distance and obstacles", "Note fences, parked cars, garden beds, stairs, or long hose runs from the street to the access point."),
            ("Flag covered or uncertain lids", "If you suspect the opening is under tiles or soil, say so. Access clarification belongs in the first conversation."),
            ("Keep safety first", "Never enter a tank space. Keep children away from open lids. Leave uncovering and handling to the service team when needed."),
        ],
        "callout_title": "Preparing for siphoning?",
        "callout_text": "Include access photos and approach notes with your location and symptoms when you request a schedule.",
        "callout_href": "prepare-for-septic-siphoning.html",
        "callout_label": "See full preparation checklist",
        "checklist": [
            "Photo of known or suspected access",
            "Distance from street or parking",
            "Obstacles or covered-lid notes",
            "Who can point out the location on-site",
        ],
        "checklist_title": "Access details to send",
        "related": [
            ("prepare-for-septic-siphoning.html", "Siphoning preparation"),
            ("septic-tank-siphoning.html", "Siphoning service"),
            ("after-siphoning-what-to-expect.html", "After siphoning"),
        ],
    },
    {
        "slug": "after-siphoning-what-to-expect",
        "title": "After Septic Siphoning: What To Expect and How to Care for the System",
        "description": "Know what to expect after septic tank siphoning, including normal observations, habits that help, and when to report new warning signs.",
        "eyebrow": "After-service care",
        "h1": "After siphoning, good habits protect the result.",
        "intro": "Service day is not the end of property care. Simple usage habits and early reporting help keep the system working more smoothly afterward.",
        "category": "Septic care",
        "summary": "A calm aftercare guide covering normal post-service expectations, prevention habits, and when to call again.",
        "image": "assets/images/septic-system.webp",
        "lead": "Siphoning restores working capacity by removing accumulated waste. How the household treats drains afterward still matters.",
        "sections": [
            ("Ask what was completed", "Before the team leaves, confirm the agreed scope and any follow-up notes about access, recurring issues, or related drainage concerns."),
            ("Resume normal use thoughtfully", "Follow any practical guidance given for your property. Avoid immediately challenging the system with grease, wipes, or heavy unnecessary load."),
            ("Keep prevention habits active", "Toilet paper only, no wipes, no grease dumping, and early reporting of slow drains remain useful after service."),
            ("Watch for returning warning signs", "If multi-fixture slowdown, odor, or backup returns quickly, report it. A different restriction may still need attention."),
            ("Record the service date", "Write down when siphoning happened. Future assessment becomes easier when history is clear."),
        ],
        "callout_title": "Symptoms returning after service?",
        "callout_text": "Share what changed, which fixtures are affected, and the recent service date so the next step can be assessed.",
        "callout_href": "contact.html",
        "callout_label": "Report a concern",
        "checklist": [
            "Save the service date",
            "Confirm any follow-up notes",
            "Keep non-flushables out",
            "Report new multi-fixture symptoms early",
        ],
        "checklist_title": "Aftercare checklist",
        "related": [
            ("what-not-to-flush-septic.html", "What not to flush"),
            ("how-often-septic-tank-siphoning.html", "Siphoning frequency"),
            ("septic-tank-warning-signs.html", "Warning signs"),
        ],
    },
    {
        "slug": "floor-drain-backup-causes",
        "title": "Floor Drain Backup: Common Causes and Next Steps",
        "description": "Learn common causes of floor drain backup in homes and businesses, safety steps to take, and when to request declogging or septic assessment.",
        "eyebrow": "Declogging guide",
        "h1": "A floor drain backup is a signal, not a small inconvenience.",
        "intro": "When water rises from a floor drain, something in the drainage path is restricted or overwhelmed. Quick observation helps identify the right response.",
        "category": "Declogging",
        "summary": "What floor drain backups can mean, how to stay safer during an event, and which details speed up professional help.",
        "image": "assets/images/declogging-equipment.webp",
        "lead": "Floor drains often reveal shared-line trouble because they sit lower in the system. Treat rising water seriously.",
        "sections": [
            ("Stop adding water to the area", "Pause laundry, showering, or mopping that sends more flow into the affected zone."),
            ("Check whether other fixtures are involved", "If toilets or sinks are also struggling, the issue may be broader than one drain opening."),
            ("Note odor and water appearance", "Wastewater odor or dirty return is different from clearer water. Include that detail when requesting help."),
            ("Keep the area clear", "Avoid splashing, keep kids away, and do not pour chemical cocktails into a rising drain."),
            ("Request assessment with context", "Tell the team where the drain is, what else is affected, and whether backup happens when another fixture is used."),
        ],
        "callout_title": "Need floor drain help?",
        "callout_text": "Send a safe photo, location, and whether multiple fixtures are involved so the likely service path can be discussed.",
        "callout_href": "declogging-services.html",
        "callout_label": "View declogging service",
        "checklist": [
            "Where the floor drain is located",
            "Whether other fixtures backup too",
            "Odor or wastewater notes",
            "When the backup started",
        ],
        "checklist_title": "Backup report details",
        "related": [
            ("septic-overflow-emergency-steps.html", "Overflow emergency steps"),
            ("slow-drains-multiple-fixtures.html", "Multiple slow drains"),
            ("restaurant-kitchen-drain-care.html", "Kitchen drain care"),
        ],
    },
    {
        "slug": "commercial-property-declogging-guide",
        "title": "Commercial Property Declogging Guide for Offices and Shops",
        "description": "A practical declogging guide for offices, shops, and commercial sites covering symptom reporting, access planning, and service coordination.",
        "eyebrow": "Commercial care",
        "h1": "Commercial sites need faster drainage decisions.",
        "intro": "Blocked restrooms or floor drains can stop business operations quickly. Clear reporting and access planning shorten the path to service.",
        "category": "Commercial care",
        "summary": "How commercial teams can prepare useful details, reduce downtime, and request declogging or septic assessment with less confusion.",
        "image": "assets/images/declogging-equipment.webp",
        "lead": "In commercial settings, the technical issue and the operations issue arrive together. Who can approve entry, where trucks can stage, and which zones are affected all matter.",
        "sections": [
            ("Identify the business impact zone", "Is it a customer restroom, staff CR, utility floor drain, or kitchen line? Priority and timing depend on what is offline."),
            ("Capture symptom scope fast", "One fixture or several floors? Odor present? Water returning? A five-line summary is enough."),
            ("Prepare access and permissions", "Security desks, parking, loading areas, and after-hours windows should be clarified early."),
            ("Decide whether septic scope may be involved", "Older buildings or sites with tank systems may need more than a local clear-out if multiple restrooms fail together."),
            ("Assign one coordinator", "A single person who can answer calls and unlock areas prevents stalled visits."),
        ],
        "callout_title": "Commercial drainage issue?",
        "callout_text": "Share site type, affected zones, access window, and symptoms for a practical assessment conversation.",
        "callout_href": "contact.html",
        "callout_label": "Coordinate commercial help",
        "checklist": [
            "Business type and affected zone",
            "Symptom summary",
            "Access and parking notes",
            "On-site coordinator contact",
        ],
        "checklist_title": "Commercial request checklist",
        "related": [
            ("restaurant-kitchen-drain-care.html", "Kitchen drain care"),
            ("apartment-building-drain-problems.html", "Building drain problems"),
            ("siphoning-vs-declogging.html", "Siphoning vs declogging"),
        ],
    },
    {
        "slug": "septic-tank-odor-outside-house",
        "title": "Septic Odor Outside the House: Causes and Practical Next Steps",
        "description": "Troubleshoot outdoor septic or wastewater odor around the yard or access point, with safety tips and details to prepare before requesting service.",
        "eyebrow": "Odor guide",
        "h1": "Outdoor wastewater odor should be traced, not ignored.",
        "intro": "A smell outside near drains, the yard, or a manhole can point to local venting, buildup, or a system that needs assessment.",
        "category": "Warning signs",
        "summary": "How to observe outdoor septic odor safely and decide when cleaning, siphoning, or broader assessment may be needed.",
        "image": "assets/images/hero-service.webp",
        "lead": "Outdoor odor is easier to dismiss than indoor backup, but it is often an earlier and cheaper time to ask for help.",
        "sections": [
            ("Pinpoint the strongest smell zone", "Yard corner, manhole area, downslope spot, or near a floor-drain exit? Location narrows possibilities."),
            ("Check for matching indoor symptoms", "If indoor drains are also slow or smelly, include that. Combined symptoms change the likely priority."),
            ("Consider recent weather and usage", "Heavy rain, guests, or a long gap since maintenance can all be useful context."),
            ("Avoid unsafe inspection methods", "Do not open tanks or lean into openings to investigate odor. Request professional assessment instead."),
            ("Send concise evidence", "A short note with location, timing, and safe photos is enough to start a useful conversation."),
        ],
        "callout_title": "Persistent outdoor odor?",
        "callout_text": "Request assessment and share whether the smell is near the access point, yard, or both.",
        "callout_href": "contact.html",
        "callout_label": "Request odor assessment",
        "checklist": [
            "Where odor is strongest",
            "Indoor symptoms, if any",
            "How long it has lasted",
            "Safe photos of the area",
        ],
        "checklist_title": "Odor report checklist",
        "related": [
            ("mabaho-ang-drain-sanhi-solusyon.html", "Mabaho ang drain guide"),
            ("pozo-negro-vs-septic-tank.html", "Pozo negro vs septic"),
            ("wet-ground-near-septic-tank.html", "Wet ground near tank"),
        ],
    },
    {
        "slug": "blocked-sink-vs-septic-issue",
        "title": "Blocked Sink vs Septic Issue: How to Tell the Difference",
        "description": "Learn how a single blocked sink differs from a septic system issue, which checks to make, and when to request declogging or tank assessment.",
        "eyebrow": "Diagnosis guide",
        "h1": "A blocked sink is not automatically a full septic tank.",
        "intro": "Kitchen and lavatory clogs are common. Use a few quick checks to see whether the problem looks local or property-wide before you request service.",
        "category": "Service guide",
        "summary": "Simple comparisons that help homeowners avoid requesting the wrong service for a sink clog.",
        "image": "assets/images/declogging-equipment.webp",
        "lead": "Guessing leads to frustration. Comparing one fixture against the rest of the property gives a clearer first request.",
        "sections": [
            ("Start with the single-fixture test", "If only one sink is slow while toilets and other drains behave normally, a local clog is more likely."),
            ("Check the nearest related fixtures", "A bathroom sink plus toilet failing together can still be a branch-line issue rather than the whole tank."),
            ("Look for septic-pattern clues", "Multiple bathrooms slowing, outdoor odor, wet ground, or wastewater return raise the chance that tank or main-line assessment is needed."),
            ("Avoid stacking random DIY chemicals", "Repeated products can add hazard without confirming the real location of the blockage."),
            ("Request the service that matches the pattern", "Local sink symptoms usually start with declogging assessment. Property-wide symptoms deserve a broader conversation."),
        ],
        "callout_title": "Still unsure after checking?",
        "callout_text": "Send which fixtures are affected and a short symptom timeline. The team can recommend the practical next step.",
        "callout_href": "services.html",
        "callout_label": "Compare service options",
        "checklist": [
            "Only one sink or several fixtures",
            "Toilet behavior in the same area",
            "Odor or backup elsewhere",
            "What has already been tried",
        ],
        "checklist_title": "Comparison checklist",
        "related": [
            ("siphoning-vs-declogging.html", "Siphoning vs declogging"),
            ("barado-ang-cr-ano-gagawin.html", "Barado ang CR"),
            ("how-to-describe-clog-for-faster-help.html", "Describe a clog clearly"),
        ],
    },
    {
        "slug": "how-to-describe-clog-for-faster-help",
        "title": "How to Describe a Clog So You Get Faster, Clearer Help",
        "description": "A simple script for describing toilet, sink, and drain clogs to a service team, including symptoms, fixtures, timing, and access details.",
        "eyebrow": "Booking guide",
        "h1": "Clear clog descriptions get clearer next steps.",
        "intro": "You do not need technical terms. You need a short, complete picture of what is happening on the property.",
        "category": "Booking guide",
        "summary": "Use this message template to request declogging or septic assessment with fewer follow-up questions.",
        "image": "assets/images/hero-service.webp",
        "lead": "Most delays in the first conversation come from missing basics: where, what fixtures, since when, and how bad. A complete first message saves time.",
        "sections": [
            ("Lead with location", "City, barangay, and a landmark. Add subdivision, building, or gate notes if they affect entry."),
            ("Name the affected fixtures", "Toilet only? Kitchen sink? Floor drain? Several bathrooms? Be specific."),
            ("Describe the symptom in plain words", "Slow, fully blocked, gurgling, water returning, odor, overflow. Short and direct is best."),
            ("Add timing and change", "When it started, whether it is worsening, and whether it followed heavy use, guests, or rain."),
            ("Attach safe photos when possible", "Access point, standing water, or the affected fixture helps. Avoid unsafe close contact with wastewater."),
        ],
        "callout_title": "Use this simple message shape",
        "callout_text": "Location + affected fixtures + symptoms + timing + access photo. That five-part message is usually enough to start.",
        "callout_href": "contact.html",
        "callout_label": "Send your request",
        "checklist": [
            "Exact location",
            "Fixture list",
            "Symptom words",
            "Start time and changes",
            "Safe photo",
        ],
        "checklist_title": "Five-part request checklist",
        "related": [
            ("prepare-for-septic-siphoning.html", "Siphoning preparation"),
            ("barado-ang-cr-ano-gagawin.html", "Barado ang CR"),
            ("contact.html", "Contact page"),
        ],
    },
    {
        "slug": "pasig-septic-service-what-to-expect",
        "title": "Pasig Septic and Declogging Service: What To Expect",
        "description": "What to expect when requesting septic siphoning, pozo negro cleaning, or declogging from a Pasig-centered service covering Metro Manila and nearby areas.",
        "eyebrow": "Local service guide",
        "h1": "What to expect from Pasig-centered septic and declogging help.",
        "intro": "From the first call to schedule confirmation, a clear process helps homeowners and businesses in Pasig and nearby areas prepare the right details.",
        "category": "Local guide",
        "summary": "A practical walkthrough of assessment, access confirmation, and service coordination for Pasig and surrounding coverage areas.",
        "image": "assets/images/hero-service.webp",
        "lead": "Jhapher Malabanan coordinates septic tank siphoning, pozo negro cleaning, and declogging with Pasig as the center area. Availability still depends on job details, access, and schedule confirmation.",
        "sections": [
            ("Start with symptoms and location", "Share your city or barangay, property type, and what you notice. Pasig requests and nearby-area requests follow the same clarity-first approach."),
            ("Expect questions about access", "Manhole location, parking, and approach distance help confirm whether the job can be planned smoothly."),
            ("Service type is confirmed from the pattern", "One blocked fixture may point to declogging. Broader slowdowns, odor, or overflow may point to tank or pozo negro assessment."),
            ("Coverage is confirmed before you rely on a schedule", "Metro Manila, Rizal, Cavite, Laguna, Bulacan, and selected extended areas are handled by confirmation, not assumption."),
            ("Urgent cases should begin with a call", "For active overflow or wastewater backup, call first. For non-urgent assessment, Viber details and photos work well."),
        ],
        "callout_title": "Request help for your area",
        "callout_text": "Send your exact location and symptoms so coverage and likely service can be confirmed.",
        "callout_href": "service-areas.html",
        "callout_label": "Check service areas",
        "checklist": [
            "City and barangay",
            "Symptom summary",
            "Access notes or photos",
            "Preferred contact path: call or Viber",
        ],
        "checklist_title": "Local request checklist",
        "related": [
            ("metro-manila.html", "Metro Manila coverage"),
            ("prepare-for-septic-siphoning.html", "Preparation checklist"),
            ("siphoning-vs-declogging.html", "Siphoning vs declogging"),
        ],
    },
]


CATEGORIES = [
    "Warning signs",
    "Service guide",
    "Declogging",
    "Septic care",
    "Booking guide",
    "Urgent help",
    "Prevention",
    "Seasonal care",
    "Property managers",
    "Commercial care",
    "Local guide",
]


def get_posts():
    return BLOG_POSTS


def get_post_slugs():
    return [post["slug"] for post in BLOG_POSTS]
